.TH COOL SIMPLE SHELL  "3rd DECEMBER, 2023" "cool - simple_shell - man page"

B.\"Manpage for simple shell (cool)

.SH NAME
simple_shell \- simple UNIX command interpreter made in C 

.SH SYNOPSIS
$ /hsh [options] [file]

.SH DESCRIPTION
This Simple Shell (cool) imitates the actual shell which is a program that takes commands from the keyboard and gives them to the Operating System (OS) for execution

.SH PATH
exit - Exit shell
env - Print a list of environment variables
setenv - Set a new environment variable
unsetenv - Unsets an environment variable
cd - Changes directories

.SH EXAMPLES
./hsh followed by command and option
$ ls -l

cd -

env

ls -l

exit 98


.SH AUTHORS
Abdulrahman Kalli Mustapha & Muhamed Adam
